### ISSUE TITLE
Onboard ORAS CLI to Snap for Ubuntu installation and provide guide

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#185]
I would like to have a command `snap install oras` to quickly install ORAS CLI on Ubuntu. I am looking for people who could help us onboard ORAS CLI to [Snap](https://snapcraft.io/about) for Ubuntu installation and provide a related guide on the ORAS website.

**Comment by SamirPS** [comment]
Hello,

@FeynmanZhou i can take this issue if you want i have already a draft snapcraft.yaml

```
 name: oras
 version: '1.0'
 summary: Package for the oras CLI tool
 description: |
   A snap package for the oras CLI tool, which is used for managing OCI artifacts.
 base: core20
 confinement: strict
 grade: stable
 
 parts:
   oras:
     plugin: go
     source: https://github.com/oras-project/oras.git
     source-type: git
     build-packages:
       - make
     override-build: |
       make "build-linux-$SNAPCRAFT_TARGET_ARCH"
       install -D -m755 bin/linux/$SNAPCRAFT_TARGET_ARCH/oras $SNAPCRAFT_PART_INSTALL/bin/oras
 
 apps:
   oras:
     command: bin/oras
     plugs:
       - home
       - network
```
